name: CI Pipeline

on:
  push:
    branches:
      - main # Adjust branch as necessary

jobs:
  terraform:
    name: Provision ECR Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Use the latest version or your preferred version
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1 
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Format
        run: terraform fmt
        
      - name: Terraform Validate
        run: terraform validate
        
      - name: Terraform Plan
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ap-south-1

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1

      - name: Build Docker image
        run: |
          docker build . -t ${{ steps.ecr-login.outputs.registry }}/my_ecr_repository:${{ github.run_number }}
          docker tag ${{ steps.ecr-login.outputs.registry }}/my_ecr_repository:${{ github.run_number }} ${{ steps.ecr-login.outputs.registry }}/my_ecr_repository:latest

      - name: Push Docker image
        run: |
          docker push ${{ steps.ecr-login.outputs.registry }}/my_ecr_repository:${{ github.run_number }}
          docker push ${{ steps.ecr-login.outputs.registry }}/my_ecr_repository:latest
